material_mapping = {
    'Aerosol': 'Metal',
    'Aluminium blister pack': 'Metal',
    'Battery': 'Other',
    'Broken glass': 'Glass',
    'Carded blister pack': 'Mixed',
    'Cigarette': 'Other',
    'Clear plastic bottle': 'Plastic',
    'Corrugated carton': 'Paper',
    'Crisp packet': 'Plastic',
    'Disposable food container': 'Plastic',
    'Disposable plastic cup': 'Plastic',
    'Drink can': 'Metal',
    'Drink carton': 'Paper',
    'Egg carton': 'Paper',
    'Foam cup': 'Plastic',
    'Foam food container': 'Plastic',
    'Food Can': 'Metal',
    'Food waste': 'Organic',
    'Garbage bag': 'Plastic',
    'Glass bottle': 'Glass',
    'Glass cup': 'Glass',
    'Glass jar': 'Glass',
    'Magazine paper': 'Paper',
    'Meal carton': 'Paper',
    'Metal bottle cap': 'Metal',
    'Metal lid': 'Metal',
    'Normal paper': 'Paper',
    'Other carton': 'Paper',
    'Other plastic': 'Plastic',
    'Other plastic bottle': 'Plastic',
    'Other plastic container': 'Plastic',
    'Other plastic cup': 'Plastic',
    'Other plastic wrapper': 'Plastic',
    'Paper bag': 'Paper',
    'Paper cup': 'Paper',
    'Paper straw': 'Paper',
    'Pizza box': 'Paper',
    'Plastic bottle cap': 'Plastic',
    'Plastic film': 'Plastic',
    'Plastic glooves': 'Plastic',
    'Plastic lid': 'Plastic',
    'Plastic straw': 'Plastic',
    'Plastic utensils': 'Plastic',
    'Polypropylene bag': 'Plastic',
    'Pop tab': 'Metal',
    'Rope - strings': 'Other',
    'Scrap metal': 'Metal',
    'Shoe': 'Other',
    'Single-use carrier bag': 'Plastic',
    'Six pack rings': 'Plastic',
    'Spread tub': 'Plastic',
    'Squeezable tube': 'Plastic',
    'Styrofoam piece': 'Plastic',
    'Tissues': 'Paper',
    'Toilet tube': 'Paper',
    'Tupperware': 'Plastic',
    'Unlabeled litter': 'Other',
    'Wrapping paper': 'Paper',
    'json': 'Other'
}
